### ISSUE TITLE
return 503 error

### ISSUE THREAD

**Issue by seriouszyx** [gafotech/sochain#2]
Hi, I used the demo codes but can't load resources.

It returns:

```
Access to fetch at 'https://chain.so/api/v2/get_info/LTCTEST' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

Can you solve my problem? tks

**Comment by mohammadrafigh** [comment]
It seems sochain has blocked CORS so there is no API access at all

**Comment by thegafo** [comment]
This package is meant to be used as a NodeJS module. It will not work in the browser.... (as @mohammadrafigh mentioned, sochain blocks CORS requests)
